language: python

python:
  - 3.6

cache:
  directories:
  - $HOME/.cache/pip

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

install:
  - pip install -r requirements-ci.txt

script:
  - pytest

notifications:
  email: false

